version = 1

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_root = "github.com/xh-polaris/meowchat-bff"

[[transformers]]
name = "gofmt"
enabled = true